name: variables and secrets

env:
  WF_VAR: "WorkFlow level variable"

on:
  push:

jobs:
  test_variables:
    env:
      JOB_VAR: "Job level variable"
    name: job to test variables
    runs-on: ubuntu-latest
    steps:
      - name: test variables
        id: stepVar
        env:
          STEP_VAR: "Step level variable"
        run: |
          echo "GitHub Actor: ${{ github.actor }}"
          echo "GitHub Job: $GITHUB_JOB"
          echo "Workflow Var: $WF_VAR"
          echo "Job Var: $JOB_VAR"
          echo "Step Var: $STEP_VAR"
          echo "Custom Var: ${{ vars.CONF_VAR }}"
          echo "Secret Var: ${{ secrets.A_SECRET }}"
